spring:
# db config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: mysql
    initialSize: 20
    minIdle: 10
    maxActive: 100
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: online.jlfsdtc.blog.dao
# server
server:
  port: 8080
# pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#logging:
#  level: info